kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shsingh-3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shsingh-3-maven
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi