apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: shsingh-3
spec:
  params:
    - default: master
      description: The git revision
      name: git-revision
    - description: The git repository url
      name: git-repo-url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: shsingh-3-run-
        labels:
          backstage.io/kubernetes-id: shsingh-3
      spec:
        params:
          - name: git-revision
            value: $(tt.params.git-revision)
        pipelineRef:
          name: shsingh-3
        serviceAccountName: pipeline
        workspaces:
          - name: source-dir
            persistentVolumeClaim:
              claimName: shsingh-3
          - name: mvn-dir
            persistentVolumeClaim:
              claimName: shsingh-3-maven
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: shsingh-3
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: gitlab-push
      name: trigger-1
      template:
        ref: shsingh-3
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: el-shsingh-3
  labels:
    app.kubernetes.io/instance: cicd-config
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: shsingh-3
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: el-shsingh-3
    weight: 100
  port:
    targetPort: http-listener
  wildcardPolicy: None